import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Add JSON parsing middleware
  app.use(express.json());

  // API routes
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", brand: "Nexcart" });
  });

  app.post("/api/orders", async (req, res) => {
    const orderData = req.body;
    console.log("Processing new order:", orderData.orderId);

    try {
      // 1. Forward to Google Sheets (Apps Script)
      const scriptUrl = process.env.GOOGLE_SHEET_APPS_SCRIPT_URL || "https://script.google.com/macros/s/AKfycby6YGxvgnFlrY5txVwjF0POHSqyntCOk1t1exVk2AhE0zxDq85JNouYqXBEtXUTYKCN/exec";
      
      try {
        await fetch(scriptUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(orderData)
        });
      } catch (sheetError) {
        console.error("Failed to update Google Sheet:", sheetError);
        // Continue even if sheet fails, as email is also important
      }

      // 2. Send Email Notification
      if (process.env.GMAIL_USER && process.env.GMAIL_APP_PASS) {
        const nodemailer = await import("nodemailer");
        const transporter = nodemailer.default.createTransport({
          service: "gmail",
          auth: {
            user: process.env.GMAIL_USER,
            pass: process.env.GMAIL_APP_PASS,
          },
        });

        const mailOptions = {
          from: `"Nexcart Notifications" <${process.env.GMAIL_USER}>`,
          to: process.env.NOTIFICATION_EMAIL || process.env.GMAIL_USER,
          subject: `🛍️ New Order Received: ${orderData.orderId}`,
          html: `
            <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden;">
              <div style="background-color: #db2777; padding: 20px; text-align: center; color: white;">
                <h1 style="margin: 0; font-size: 24px;">New Order Placed!</h1>
              </div>
              <div style="padding: 30px;">
                <h2 style="color: #1e293b; margin-top: 0;">Order #${orderData.orderId}</h2>
                <p style="color: #64748b; line-height: 1.6;">A new order has been placed on Nexcart and successfully added to the Google Sheet.</p>
                
                <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
                  <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                      <td style="padding: 8px 0; color: #64748b; font-weight: bold;">Customer:</td>
                      <td style="padding: 8px 0; color: #1e293b;">${orderData.firstName} ${orderData.lastName}</td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #64748b; font-weight: bold;">Phone:</td>
                      <td style="padding: 8px 0; color: #1e293b;">${orderData.phone}</td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #64748b; font-weight: bold;">Amount:</td>
                      <td style="padding: 8px 0; color: #db2777; font-weight: bold;">₹${orderData.totalAmount}</td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #64748b; font-weight: bold;">Payment:</td>
                      <td style="padding: 8px 0; color: #1e293b;">${orderData.paymentMethod}</td>
                    </tr>
                  </table>
                </div>

                <h3 style="color: #1e293b; font-size: 16px; margin-top: 25px;">Products:</h3>
                <p style="color: #1e293b; background: #fff1f2; padding: 10px; border-radius: 6px; border-left: 4px solid #db2777;">
                  ${orderData.products}
                </p>

                <div style="margin-top: 30px; border-top: 1px solid #e2e8f0; pt: 20px;">
                  <p style="color: #64748b; font-size: 14px; font-weight: bold;">Shipping Address:</p>
                  <p style="color: #1e293b; font-size: 14px; line-height: 1.6;">
                    ${orderData.address}<br>
                    ${orderData.city}, ${orderData.pincode}
                  </p>
                </div>
              </div>
              <div style="background-color: #f1f5f9; padding: 15px; text-align: center; color: #94a3b8; font-size: 12px;">
                Generated by Nexcart Order System
              </div>
            </div>
          `,
        };

        await transporter.sendMail(mailOptions);
        console.log("Email notification sent for order:", orderData.orderId);
      } else {
        console.warn("Email configuration missing. Notification skipped.");
      }

      res.status(200).json({ success: true, message: "Order processed successfully" });
    } catch (error) {
      console.error("Order processing error:", error);
      res.status(500).json({ success: false, error: "Internal server error" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Nexcart Server running on http://localhost:${PORT}`);
  });
}

startServer();
