import { Product } from "../types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    sellerId: "s1",
    name: "Apple iPhone 15 Pro (128GB) - Blue Titanium",
    description: "The latest iPhone with Titanium design and A17 Pro chip.",
    price: 129900,
    originalPrice: 134900,
    category: "electronics",
    images: ["https://picsum.photos/seed/iphone/800/800"],
    stock: 50,
    ratings: 4.8,
    numReviews: 1240,
    isTrending: true,
    createdAt: Date.now()
  },
  {
    id: "d1",
    sellerId: "s2",
    name: "Urban Oversized Graphic Tee - Vintage Black",
    description: "Premium cotton oversized t-shirt with high-quality graphic print.",
    price: 899,
    originalPrice: 1499,
    category: "fashion",
    images: ["https://picsum.photos/seed/tee/800/800"],
    stock: 100,
    ratings: 4.5,
    numReviews: 850,
    isFlashDeal: true,
    isTrending: false,
    isNew: true,
    createdAt: Date.now()
  },
  {
    id: "g1",
    sellerId: "s3",
    name: "NexBuds Lite Wireless Earbuds",
    description: "Affordable wireless earbuds with deep bass and 20h battery life.",
    price: 1299,
    originalPrice: 2499,
    category: "gadgets",
    images: ["https://picsum.photos/seed/buds/800/800"],
    stock: 200,
    ratings: 4.3,
    numReviews: 3200,
    isFlashDeal: true,
    isTrending: true,
    isNew: true,
    createdAt: Date.now()
  },
  {
    id: "d2",
    sellerId: "s2",
    name: "Floral A-Line Summer Dress",
    description: "Lightweight and breathable floral dress perfect for summer outings.",
    price: 2499,
    originalPrice: 3999,
    category: "fashion",
    images: ["https://picsum.photos/seed/dress/800/800"],
    stock: 45,
    ratings: 4.7,
    numReviews: 120,
    isFlashDeal: false,
    isTrending: true,
    createdAt: Date.now()
  },
  {
    id: "g2",
    sellerId: "s3",
    name: "Portable LED Desk Lamp",
    description: "Low-price rechargeable LED lamp with adjustable brightness.",
    price: 499,
    originalPrice: 999,
    category: "gadgets",
    images: ["https://picsum.photos/seed/lamp/800/800"],
    stock: 150,
    ratings: 4.6,
    numReviews: 450,
    isFlashDeal: true,
    isTrending: false,
    createdAt: Date.now()
  },
  {
    id: "g3",
    sellerId: "s1",
    name: "Ultra-Thin Power Bank 10,000mAh",
    description: "Compact power bank that fits right in your pocket.",
    price: 999,
    originalPrice: 1999,
    category: "gadgets",
    images: ["https://picsum.photos/seed/power/800/800"],
    stock: 500,
    ratings: 4.6,
    numReviews: 5600,
    isFlashDeal: true,
    isTrending: true,
    createdAt: Date.now()
  },
  {
    id: "d3",
    sellerId: "s2",
    name: "Casual Evening Party Gown",
    description: "Elegant silk blend gown for special occasions.",
    price: 5999,
    originalPrice: 8999,
    category: "fashion",
    images: ["https://picsum.photos/seed/gown/800/800"],
    stock: 25,
    ratings: 4.9,
    numReviews: 45,
    isFlashDeal: false,
    isTrending: true,
    createdAt: Date.now()
  }
];
